[tool.poetry]
name = "dbgpy"
version = "0.1.1"
description = "Python implementation of Rust's dbg! macro"
authors = ["Marcel RÃ¸d <marcelroed@gmail.com>"]
license = "MIT"
repository = "https://github.com/marcelroed/dbgpy"

[tool.poetry.dependencies]
python = "^3"
torch = {version = "^1", optional = true}
astunparse = {version = "^1", markers = "python_version<'3.9'"}

[tool.poetry.dev-dependencies]
pytest = "*"
black = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
