[tool.poetry]
name = "lel-python-daemonize"
version = "0.1.0"
description = ""
authors = ["LÃ©o El Amri <leo@superlel.me>"]
license = "MIT"
repository = "https://github.com/lel-amri/lel-python-daemonize"
packages = [
    { include = "daemonize.py" }
]

[tool.poetry.dependencies]
python = "3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
