[tool.poetry]
name = "pycbf"
version = "0.9.6.4"
description = "An API for CBF/imgCIF Crystallographic Binary Files"
homepage="http://www.bernstein-plus-sons.com/software/CBF/"
authors = ["Herbert J. Bernstein <yaya@bernstein-plus-sons.com>", "Paul J. Ellis"]
maintainers = ["Nicholas Devenish <ndevenish@gmail.com>"]
license = "LGPL-2.1-or-later"
readme="README.md"
build = "build.py"
repository="https://github.com/dials/pycbf"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering",
]
include = [
    {path = "pycbf_wrap.c", format = "sdist"},
    {path = "LICENCE.txt", format = "sdist"},
    {path = "cbflib/src/*.c", format = "sdist"},
    {path = "cbflib/include/*.h", format = "sdist"},
    {path = "src/pycbf/py.typed"},
]


[tool.poetry.dependencies]
python = ">=3.6.0"
numpy = ">=1.17"

[tool.poetry.dev-dependencies]
setuptools = "^56.1.0"
Cython = "^0.29.23"
toml = "^0.10.2"
pytest = "^6.2.4"
dials-data = ">=2.1.58"
bump2version = "^1.0.1"

[build-system]
requires = [
    "poetry-core>=1.0.0",
    "setuptools",
    "Cython~=0.29.23",
]
build-backend = "poetry.core.masonry.api"

[tool.black]
exclude = "cbflib/|src/pycbf/__init__.py"

[tool.isort]
skip = [ "cbflib/", "setup.py", "src/pycbf/__init__.py"]

[tool.towncrier]
package = "pycbf"
package_dir = ".."
filename = "CHANGELOG.rst"

[tool.pytest.ini_options]
addopts = "--regression -ra"
testpaths = [
    "tests",
]
